project:
  type: website
  output-dir: docs

website: 
  title: "FIP_606 - Análise e Visualização de Dados em Fitopatologia"

  navbar:
    background: "#DDA0DD"
    foreground: "#000000"
    left:
      - text: "Sobre"
        file: index.qmd
        icon: info-circle
      - text: "Introdução ao R"
        file: introducao.qmd
      - text: "Manipulação"
        file: aula2.qmd
      - text: "Dataframe"
        file: dataframe.qmd
      - text: "Distribuição"
        file: graficosdisp.qmd
      - text: "BoxPlot"
        file: ggplot2.qmd
      - text: "Box-Cox"
        file: boxcox.qmd
      - text: "Hipótese"
        file: hipotese.qmd
      - text: "Transformação"
        file: transformacao.qmd
      - text: "Teste T"   
        file: testt.qmd
      - text: "ANOVA"  
        file: anova.qmd
      - text: "Correlação"    
        file: correlacao.qmd
      - text: "Regressão"
        file: regressao.qmd
        

    right:
      - text: "Maria Izabel"
        href: https://github.com/izabelalmeidal/FIP-606-Analise-e-visualiza-o-de-dados-em-Fitopatologia
        icon: github
      - icon: envelope
        href: "mailto:maria.a.leite@ufv.br"

  page-footer:
    left: "© 2025 - Maria Izabel de Almeida Leite — Feito com [Quarto](https://quarto.org)"

format:
  html:
    theme:
      light: minty
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    code-tools: true
    code-fold: true
    code-line-numbers: true
    warning: false
    message: false
    echo: true

metadata:
  author: "Maria Izabel de Almeida Leite"

execute:
  echo: true
  warning: false
  message: false
  error: false
  output: true
  cache: false
